/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ltudor' at '3/16/17 8:44 PM' with Gradle 2.13
 *
 * @author ltudor, @date 3/16/17 8:44 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
